service: swissitize
image: margarita2104/swissitize

servers:
  web:
    - 116.203.85.111
    - healthcheck:
        port: 3000
        path: /up  # Change from /health to /up
        interval: 10s
        timeout: 5s
        start_period: 30s

proxy:
  ssl: true
  host: swissitize.apps.rubymonstas.ch

registry:
  server: ghcr.io
  username: margarita2104
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "swissitize_app_storage:/rails/storage"
  # - "swissitize_public_assets:/rails/public/assets"

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"