service: swissitize
image: margarita2104/swissitize
servers:
  web:
    - 116.203.85.111

proxy:
  ssl: true
  host: swissitize.apps.rubymonstas.ch

registry:
  server: ghcr.io
  username: margarita2104
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "swissitize_db:/rails/db"
  - "swissitize_storage:/rails/storage"
  # - "swissitize_public_assets:/rails/public/assets"

asset_path: /rails/public/assets

healthcheck:
  max_attempts: 10  # Add this to give more time for db setup
  interval: 5s      # Check every 5 seconds