service: swissitize
image: margarita2104/swissitize

servers:
  web:
    - 116.203.85.111

proxy:
  ssl: true
  host: swissitize.apps.rubymonstas.ch

registry:
  server: ghcr.io
  username: margarita2104
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
    - GMAIL_DOMAIN
    - GMAIL_USERNAME
    - GMAIL_PASSWORD

volumes:
  - "swissitize_sqlite:/rails/db/production.sqlite3"
  - "swissitize_storage:/rails/storage"
  # - "swissitize_assets:/rails/public/assets"  # Single assets volume

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"